ROUTE_SAMPLES = {
    "/api/admin/service-integrations/<service_integration_id>": "/api/admin/service-integrations/svc-1",
    "/api/admin/users/<user_id>": "/api/admin/users/user-1",
    "/api/admin/users/<user_id>/admin-grant": "/api/admin/users/user-1/admin-grant",
    "/api/admin/users/<user_id>/status": "/api/admin/users/user-1/status",
    "/api/epm/projects/<path:home_project_id>/issues": "/api/epm/projects/home-project-1/issues",
    "/api/epm/projects/<path:project_id>/rollup": "/api/epm/projects/home-project-1/rollup",
    "/api/me/views/<view_id>": "/api/me/views/view-1",
    "/api/scenario/drafts/<draft_id>/events": "/api/scenario/drafts/draft-1/events",
    "/api/scenario/drafts/<draft_id>/events/stream": "/api/scenario/drafts/draft-1/events/stream",
    "/api/scenario/drafts/<draft_id>/locks": "/api/scenario/drafts/draft-1/locks",
    "/api/scenario/drafts/<draft_id>/presence": "/api/scenario/drafts/draft-1/presence",
    "/api/scenario/drafts/<draft_id>/reload-from-jira": "/api/scenario/drafts/draft-1/reload-from-jira",
    "/api/scenario/drafts/<draft_id>/rollback": "/api/scenario/drafts/draft-1/rollback",
    "/api/scenario/drafts/<draft_id>/versions/<int:version_number>": "/api/scenario/drafts/draft-1/versions/1",
    "/api/scenario/drafts/<draft_id>/writeback": "/api/scenario/drafts/draft-1/writeback",
    "/api/scenario/drafts/<draft_id>/writeback/preview": "/api/scenario/drafts/draft-1/writeback/preview",
    "/frontend/dist/<path:filename>": "/frontend/dist/dashboard.js",
    "/static/<path:filename>": "/static/missing.txt",
}
